name: poc-cqrs-pgl

networks:
  pgl-cqrs-net:

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    networks:
      - pgl-cqrs-net
  
  write-db:
    image: bitnami/postgresql
    hostname: write-db
    environment:
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_user
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: 12345
      POSTGRESQL_DATABASE: testdb
      ALLOW_EMPTY_PASSWORD: yes
      POSTGRESQL_PORT_NUMBER: 5433
    healthcheck: &pg_healthcheck
      test: 
        [ "CMD", "pg_isready", "-d", "${POSTGRESQL_DATABASE}", "-U", "${POSTGRESQL_USERNAME:-admin}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5433:5433"
    networks:
      - pgl-cqrs-net
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  read-db:
    image: bitnami/postgresql
    hostname: read-db
    environment:
      POSTGRESQL_PASSWORD: 12345
      POSTGRESQL_MASTER_HOST: write-db
      POSTGRESQL_PGAUDIT_LOG: READ
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_user
      POSTGRESQL_MASTER_PORT_NUMBER: 5433
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      <<: *pg_healthcheck
    depends_on:
      - write-db
    ports:
      - "5432:5432"
    networks:
      - pgl-cqrs-net
  
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pgl-cqrs-net

  writer:
    build: ./writer
    ports:
      - "8081:8080"
    networks:
      - pgl-cqrs-net
    depends_on:
      - write-db
      - rabbitmq
  
  reader:
    build: ./reader
    ports:
      - "8082:8080"
    networks:
      - pgl-cqrs-net
    depends_on:
      - read-db
      - rabbitmq

  log-consumer:
    build: ./log-consumer
    networks:
      - pgl-cqrs-net
    depends_on:
      - rabbitmq