CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'replicator_password';
SELECT pg_create_physical_replication_slot('replication_slot');

create schema test_schema;

create table test_schema.books
(
    id     integer
        constraint books_pk
            primary key,
    title  varchar(128),
    author varchar(128)
);

insert into test_schema.books (id, title, author) values (1, 'Parisienne, La (Une parisienne)', 'Billy Toppes');
insert into test_schema.books (id, title, author) values (2, 'Ginger Snaps', 'Kalie Nashe');
insert into test_schema.books (id, title, author) values (3, 'Bloodsuckers', 'Ruth Browell');
insert into test_schema.books (id, title, author) values (4, 'Berlin Express', 'April Dolman');
insert into test_schema.books (id, title, author) values (5, 'Battle of Shaker Heights, The', 'Rayna Marrable');
insert into test_schema.books (id, title, author) values (6, 'Timecop', 'Ally Groucock');
insert into test_schema.books (id, title, author) values (7, 'Into the Storm', 'Avram Kerswill');
insert into test_schema.books (id, title, author) values (8, 'Nadine', 'Jackquelin Stowe');
insert into test_schema.books (id, title, author) values (9, 'Temptation (Tentação)', 'Herold Tyers');
insert into test_schema.books (id, title, author) values (10, 'Block Party (a.k.a. Dave Chappelle''s Block Party)', 'Xymenes Feare');
insert into test_schema.books (id, title, author) values (11, 'King Lear (Korol Lir)', 'Gard Le feuvre');
insert into test_schema.books (id, title, author) values (12, 'Shock', 'Arnold Van der Hoven');
insert into test_schema.books (id, title, author) values (13, 'The Horseplayer', 'Caddric Innocenti');
insert into test_schema.books (id, title, author) values (14, 'Female', 'Jule Ellin');
insert into test_schema.books (id, title, author) values (15, 'Rio 2', 'Doris Barkus');
insert into test_schema.books (id, title, author) values (16, 'Line King: The Al Hirschfeld Story, The', 'Myer Edyson');
insert into test_schema.books (id, title, author) values (17, 'Two Years at Sea', 'Tamma Viste');
insert into test_schema.books (id, title, author) values (18, 'Woods, The', 'Betsy Briskey');
insert into test_schema.books (id, title, author) values (19, 'Three Days of the Condor (3 Days of the Condor)', 'Wilmer Babar');
insert into test_schema.books (id, title, author) values (20, 'Merchant of Venice, The', 'Claus Biddleston');
insert into test_schema.books (id, title, author) values (21, 'Craig Ferguson: Does This Need to Be Said?', 'Ban Jiggle');
insert into test_schema.books (id, title, author) values (22, 'Fat, Sick & Nearly Dead 2', 'Sofia Lossman');
insert into test_schema.books (id, title, author) values (23, 'Cantante, El', 'Vidovic Itzkovsky');
insert into test_schema.books (id, title, author) values (24, 'Nocturna', 'Stefan Peploe');
insert into test_schema.books (id, title, author) values (25, 'In a World...', 'Cosetta Hendrik');
insert into test_schema.books (id, title, author) values (26, 'End of Poverty, The', 'Morris Jerram');
insert into test_schema.books (id, title, author) values (27, 'Cabin in the Woods, The', 'Leonardo Tevelov');
insert into test_schema.books (id, title, author) values (28, 'Show People', 'Eryn Cant');
insert into test_schema.books (id, title, author) values (29, 'Out On A Limb', 'Ricky Kimbley');
insert into test_schema.books (id, title, author) values (30, 'Mirage Men', 'Nellie Goudie');
insert into test_schema.books (id, title, author) values (31, 'White Angel, The (L''angelo bianco)', 'Freemon Pask');
insert into test_schema.books (id, title, author) values (32, 'The Encounter', 'Kandace Fitzroy');
insert into test_schema.books (id, title, author) values (33, 'Fanny', 'Dita Poppleston');
insert into test_schema.books (id, title, author) values (34, 'Leo the Last', 'Giacobo Bolzmann');
insert into test_schema.books (id, title, author) values (35, 'Children''s Hour, The', 'Mia Ellsom');
insert into test_schema.books (id, title, author) values (36, 'House with Laughing Windows, The (Casa dalle finestre che ridono, La)', 'Benita Huckerbe');
insert into test_schema.books (id, title, author) values (37, 'Life''s a Breeze', 'Willdon Fennick');
insert into test_schema.books (id, title, author) values (38, 'Stone Left Unturned, A (Kovat miehet)', 'Pearl Partleton');
insert into test_schema.books (id, title, author) values (39, 'Shadow of the Thin Man', 'Moina Suett');
insert into test_schema.books (id, title, author) values (40, 'Ship of Fools', 'Adelina McKerley');
insert into test_schema.books (id, title, author) values (41, 'Wing Commander', 'Angelina Gainsborough');
insert into test_schema.books (id, title, author) values (42, 'Grandpa for Christmas, A (Bert & Becca)', 'Ivett Foulger');
insert into test_schema.books (id, title, author) values (43, 'Mein Kampf', 'Rianon Mussen');
insert into test_schema.books (id, title, author) values (44, 'The Hunting Ground', 'Margaux Cashford');
insert into test_schema.books (id, title, author) values (45, 'Breaking the Girls ', 'Carlina Rate');
insert into test_schema.books (id, title, author) values (46, 'Wirey Spindell', 'Shayla Helgass');
insert into test_schema.books (id, title, author) values (47, 'Hello, Dolly!', 'Angie Edmands');
insert into test_schema.books (id, title, author) values (48, 'Junkopia', 'Lorette Kirk');
insert into test_schema.books (id, title, author) values (49, 'Please Don''t Eat the Daisies', 'Shannon Lux');
insert into test_schema.books (id, title, author) values (50, 'Cop Out', 'Danya Imison');
insert into test_schema.books (id, title, author) values (51, 'Your Sister''s Sister', 'Pembroke Perocci');
insert into test_schema.books (id, title, author) values (52, 'Knick Knack', 'Stanley Chrishop');
insert into test_schema.books (id, title, author) values (53, 'Chicks with Sticks', 'Fanya Shingles');
insert into test_schema.books (id, title, author) values (54, 'This American Journey', 'Roselia Alvaro');
insert into test_schema.books (id, title, author) values (55, 'Mirrors', 'Pegeen Giacomazzo');
insert into test_schema.books (id, title, author) values (56, 'Sacred Heart', 'Raimundo Frangello');
insert into test_schema.books (id, title, author) values (57, 'Scary Movie', 'Steffen McGoon');
insert into test_schema.books (id, title, author) values (58, 'Fading Gigolo', 'Jessalyn Gillingham');
insert into test_schema.books (id, title, author) values (59, 'Black Nativity', 'Megan Kingsnod');
insert into test_schema.books (id, title, author) values (60, 'What! No Beer?', 'Mady Shattock');
insert into test_schema.books (id, title, author) values (61, 'Tunnel Rats (1968 Tunnel Rats)', 'Merwyn Murdie');
insert into test_schema.books (id, title, author) values (62, 'King of New York', 'Newton Jiroutek');
insert into test_schema.books (id, title, author) values (63, 'Hedda Gabler', 'Boone Woodyatt');
insert into test_schema.books (id, title, author) values (64, 'United', 'Ephraim Trusdale');
insert into test_schema.books (id, title, author) values (65, 'The Moromete Family', 'Amble Binestead');
insert into test_schema.books (id, title, author) values (66, 'Super Rich: The Greed Game', 'Lanita Dyment');
insert into test_schema.books (id, title, author) values (67, 'Riding Giants', 'Marchelle Dovinson');
insert into test_schema.books (id, title, author) values (68, 'Touch of Pink', 'Elizabet Hegarty');
insert into test_schema.books (id, title, author) values (69, 'All''s Well', 'Simonne Eyden');
insert into test_schema.books (id, title, author) values (70, 'Sarafina!', 'Crin Priddie');
insert into test_schema.books (id, title, author) values (71, 'Paradise Lost 3: Purgatory', 'Allx Opfer');
insert into test_schema.books (id, title, author) values (72, 'Marilyn Hotchkiss'' Ballroom Dancing & Charm School', 'Jess Halfpenny');
insert into test_schema.books (id, title, author) values (73, 'Captivity', 'Sharline Mulqueeny');
insert into test_schema.books (id, title, author) values (74, 'Faces of Death 5', 'Giulietta Logie');
insert into test_schema.books (id, title, author) values (75, 'Titanic', 'Coralyn Weeks');
insert into test_schema.books (id, title, author) values (76, 'Children of the Corn: Genesis', 'Gus Wholesworth');
insert into test_schema.books (id, title, author) values (77, 'Dying of Laughter (Muertos de Risa)', 'Agustin O Mullen');
insert into test_schema.books (id, title, author) values (78, 'Dead Reckoning', 'Chevy Tibbs');
insert into test_schema.books (id, title, author) values (79, 'Three Stooges Meet Hercules, The', 'Bethina Conklin');
insert into test_schema.books (id, title, author) values (80, 'Inland Empire', 'Debby Nickerson');
insert into test_schema.books (id, title, author) values (81, 'Broadway Melody of 1938', 'Jorge Ourtic');
insert into test_schema.books (id, title, author) values (82, 'Kite Runner, The', 'Raychel Ratcliff');
insert into test_schema.books (id, title, author) values (83, 'Sky Murder', 'Derward Gabbitis');
insert into test_schema.books (id, title, author) values (84, 'Assignment, The', 'Romona Nisius');
insert into test_schema.books (id, title, author) values (85, 'Peppermint Candy (Bakha satang)', 'Rubina Thorne');
insert into test_schema.books (id, title, author) values (86, 'Arranged', 'Koralle Firby');
insert into test_schema.books (id, title, author) values (87, 'West of the Divide', 'Sibby Gilks');
insert into test_schema.books (id, title, author) values (88, 'Dilwale Dulhania Le Jayenge', 'Hillary Hayward');
insert into test_schema.books (id, title, author) values (89, 'Nightbreed', 'Mei Hallut');
insert into test_schema.books (id, title, author) values (90, 'The Killing Jar', 'Tricia Ranyell');
insert into test_schema.books (id, title, author) values (91, 'Too Late Blues', 'Rawley Charley');
insert into test_schema.books (id, title, author) values (92, 'Live Nude Girls Unite!', 'Cody Domeny');
insert into test_schema.books (id, title, author) values (93, 'Victory (a.k.a. Escape to Victory)', 'Sacha Byre');
insert into test_schema.books (id, title, author) values (94, 'Maniac', 'Cathi Rameau');
insert into test_schema.books (id, title, author) values (95, 'Freeze Frame', 'Marijn Careless');
insert into test_schema.books (id, title, author) values (96, 'Adventures of Food Boy, The (aka High School Superhero)', 'Kayley Richardes');
insert into test_schema.books (id, title, author) values (97, 'Carried Away', 'Gayel Jessel');
insert into test_schema.books (id, title, author) values (98, 'Dragon Seed', 'Grethel Lung');
insert into test_schema.books (id, title, author) values (99, 'Wild Geese, The', 'Vernon Axell');
insert into test_schema.books (id, title, author) values (100, 'Wing Chun', 'Jourdan Taill');
