apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-consumer
  labels:
    app: log-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-consumer
  template:
    metadata:
      labels:
        app: log-consumer
    spec:
      containers:
        - name: log-consumer
          image: docker.io/arkensa/log-consumer:latest
          imagePullPolicy: IfNotPresent
          # Add env, ports, etc. as needed