apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-db
  labels:
    app: read-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read-db
  template:
    metadata:
      labels:
        app: read-db
    spec:
      containers:
        - name: read-db
          image: bitnami/postgresql
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poc-secrets
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_MASTER_HOST
              value: "write-db"
            - name: POSTGRESQL_PGAUDIT_LOG
              value: "READ"
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "true"
            - name: POSTGRESQL_REPLICATION_MODE
              value: "slave"
            - name: POSTGRESQL_REPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: poc-secrets
                  key: POSTGRESQL_REPLICATION_USER
            - name: POSTGRESQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poc-secrets
                  key: POSTGRESQL_REPLICATION_PASSWORD
            - name: POSTGRESQL_MASTER_PORT_NUMBER
              value: "5432"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"