apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  labels:
    app: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
        - name: writer
          image: docker.io/arkensa/writer:latest
          imagePullPolicy: Always
          env:
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: pcg-secrets
                  key: KEYCLOAK_PUBLIC_KEY
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: pcg-secrets
                  key: DB_URL
            # Add any other needed env vars from your .env here