apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  labels:
    app: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
        - name: writer
          image: docker.io/arkensa/writer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: poc-secrets
                  key: KEYCLOAK_PUBLIC_KEY
            - name: PGPOOL_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: poc-secrets
                  key: PGPOOL_POSTGRES_USERNAME
            - name: PGPOOL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poc-secrets
                  key: PGPOOL_POSTGRES_PASSWORD
            - name: PGPOOL_NAME
              valueFrom:
                secretKeyRef:
                  name: poc-secrets
                  key: PGPOOL_NAME
            # Add any other needed env vars from your .env here